apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vyhn6qjb3-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6d79b041ed.puy2.p3.openshiftapps.com/rhtap/rhtap-qe:f542075884815f060fac64fc183a2320d3fed483@sha256:ae63203a31613362a635793bbbd95f263c566f890e7c9363d838aa8ee587af87
          name: container-image
